name: Build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
  docker:
    name: Docker Build
    needs:
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: BuildKit
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Last commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.current-time.outputs.time }}
            COMMIT_SHA=${{ steps.vars.outputs.sha_short }}
          tags: |
            docker.io/${{ github.repository_owner }}/openconnect:latest
            docker.io/${{ github.repository_owner }}/openconnect:${{ steps.vars.outputs.sha_short }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ github.repository_owner }}/openconnect
          readme-filepath: ./README.md